# Generated by Django 5.2.4 on 2025-08-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_quest_app', '0002_alter_quiz_options_remove_question_answer_open_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='banned',
            field=models.BooleanField(default=False),
        ),
    ]
