# Generated by Django 5.2.4 on 2025-08-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_quest_app', '0004_userprofile_banned_date_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='banned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
